version: 0.2.0[{build}]

clone_depth: 1

branches:
  only:
    - master
    - dev

cache:
  - c:\usr
  - c:\tools\vcpkg\installed\

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  VULKAN_SDK: C:\VulkanSDK\1.2.135.0
  matrix:
    - CMAKE_VS_VERSION: "15 2017"

install:
  - curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.2.135.0/windows/VulkanSDK-1.2.135.0-Installer.exe?Human=true
  - .\VulkanSDK.exe /S
  - appveyor DownloadFile https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip -FileName glslangvalidator.zip
  - unzip glslangvalidator.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\bin;%PATH%
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg --disable-metrics install capnproto:%platform%-windows
  - cd C:\Tools\vcpkg
  - vcpkg --disable-metrics integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - git submodule -q update --init --recursive
  - cmake -DCMAKE_PREFIX_PATH=C:/Tools/vcpkg/packages/capnproto_%platform%-windows/ -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64 -DSTANDALONE=ON -DCMAKE_BUILD_TYPE=%configuration% -G "Visual Studio %CMAKE_VS_VERSION%"

build_script:
  project: ALL_BUILD.vcxproj
  verbosity: minimal
